"""empty message

Revision ID: c7b96e77ffb5
Revises: 2eee169a9dab
Create Date: 2022-04-14 11:43:54.675477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7b96e77ffb5'
down_revision = '2eee169a9dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lifts')
    op.add_column('workouts', sa.Column('lift', sa.String(length=32), nullable=False))
    op.add_column('workouts', sa.Column('sets', sa.Integer(), nullable=True))
    op.add_column('workouts', sa.Column('reps', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'reps')
    op.drop_column('workouts', 'sets')
    op.drop_column('workouts', 'lift')
    op.create_table('lifts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lift', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('sets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('workout_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name='lifts_workout_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='lifts_pkey')
    )
    # ### end Alembic commands ###
